### ISSUE TITLE
Project Setup and Firebase Configuration

### ISSUE THREAD

**Issue by Shareef2845** [Shareef2845/IRTC_Ticket_Booking_Application_React#1]
Set up the Flutter project and configure Firebase integration.

### Tasks
- [ ] Create new Flutter project
- [ ] Add required dependencies in pubspec.yaml
- [ ] Configure Firebase project
- [ ] Add Firebase configuration files
- [ ] Initialize Firebase in the app

### Dependencies to add
```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  cached_network_image: ^3.2.3
```

### Implementation Steps
1. Create project using:
```bash
flutter create ecommerce_app
cd ecommerce_app
```

2. Set up Firebase:
- Create new Firebase project
- Add Android and iOS apps
- Download and add configuration files
- Initialize Firebase in main.dart
